"""
A Transformer decoder, composed from broccoli's primitives: causal
self-attention and cross-attention into a fixed memory, both inside every
block. broccoli has no such stack of its own.

`DecoderBlock` mirrors `broccoli.transformer.EncoderBlock` closely, with one
extra sublayer between the self-attention and the feedforward; what this file
adds is wiring, so a change to broccoli's attention or feedforward reaches here
too. See docs/architecture.md and docs/broccoli.md.
"""

import torch
import torch.nn as nn
from torch.utils.checkpoint import checkpoint

import broccoli
from broccoli.rope import RotaryEmbedding


class DecoderBlock(nn.Module):
    """
    One decoder layer: self-attention, then cross-attention into a memory, then
        a feedforward, each on its own residual branch. `causal` masks the
        self-attention and `cross_first` swaps the first two branches; the
        defaults are the speaker's.

    Three branches, so a stack built from these must ask
        `model_util.deepnorm_constants` for `decoder=True`.

    Stochastic depth is drawn inside `forward`, and the same mask is shared by
        all three branches so a dropped block is the identity. Note a speaker
        runs this stack once per symbol, so each position of a message is
        generated by an independent draw -- see docs/architecture.md.
    """

    def __init__(
        self,
        seq_len,
        memory_len,
        d_model,
        n_heads,
        relative_position_embedding=False,
        positional_heads=1.0,
        source_size=None,
        bos_tokens=0,
        knocking_heads=False,
        ff_ratio=None,
        ff_inner_size=None,
        activation=nn.ReLU,
        activation_kwargs=None,
        msa_scaling="d",
        ff_dropout=0.0,
        ff_inner_dropout=0.0,
        ff_outer_dropout=0.0,
        msa_dropout=0.0,
        cross_attention_dropout=0.0,
        identity_probability=0.0,
        linear_module=nn.Linear,
        pre_norm=False,
        post_norm=True,
        alpha=1.0,
        beta=1.0,
        causal=True,
        cross_first=False,
    ):
        """
        Args:
            seq_len: length of the sequence being decoded, including any
                `bos_tokens` prefix. The causal mask is square over this, and
                is inert when `causal` is False.
            memory_len: length of the array being cross-attended into. Recorded
                for the caller's benefit and sizes nothing: the cross-attention
                is not causal, so it needs no mask.
            causal: mask the self-attention left to right. True for a speaker
                generating a sequence; False wherever the axis is a set rather
                than an order, as the listener's candidates are. See
                docs/architecture.md.
            cross_first: read the memory before the sequence reads itself,
                rather than after. The listener's referent stack wants this so
                that candidates compare message-informed representations; a
                speaker wants the default.
        """
        super().__init__()

        if pre_norm and post_norm:
            raise ValueError("A transformer cannot be both prenorm and postnorm.")

        self.n_heads = n_heads
        self.seq_len = seq_len
        self.memory_len = memory_len

        self.pre_norm = pre_norm
        self.post_norm = post_norm

        self.alpha = alpha
        self.beta = beta
        self.causal = causal
        self.cross_first = cross_first

        self.identity_probability = identity_probability

        if self.pre_norm:
            self.pre_attention_norm = nn.RMSNorm(d_model)
            self.pre_cross_attention_norm = nn.RMSNorm(d_model)
            self.pre_mlp_norm = nn.RMSNorm(d_model)

        if self.post_norm:
            self.post_attention_norm = nn.RMSNorm(d_model)
            self.post_cross_attention_norm = nn.RMSNorm(d_model)
            self.post_mlp_norm = nn.RMSNorm(d_model)

        # Built here rather than taken as an argument, mirroring `EncoderBlock`:
        #     each block owns its own frequencies.
        if relative_position_embedding:
            max_freq = int(max(source_size) / 2)
            dim = d_model if d_model < 16 else 16
            self.rotary_embedding = RotaryEmbedding(
                dim=dim, freqs_for="pixel", max_freq=max_freq
            )
        else:
            self.rotary_embedding = None

        self.self_attention = broccoli.transformer.MHAttention(
            d_model,
            n_heads,
            dropout=msa_dropout,
            causal=causal,
            seq_len=seq_len,
            linear_module=linear_module,
            bos_tokens=bos_tokens,
            knocking_heads=knocking_heads,
            rotary_embedding=self.rotary_embedding,
            positional_heads=positional_heads,
            source_size=source_size,
            scaling=msa_scaling,
        )

        # No positional information on either side: the queries carry the
        #     decoder's own order and the memory's is already baked in. See
        #     docs/broccoli.md for the pinned arguments.
        self.cross_attention = broccoli.transformer.MHAttention(
            d_model,
            n_heads,
            dropout=cross_attention_dropout,
            causal=False, # Whole memory informs every position
            seq_len=seq_len,
            linear_module=linear_module,
            bos_tokens=0,
            knocking_heads=False,
            rotary_embedding=None,
            positional_heads=1.0,
            source_size=None,
            scaling=msa_scaling,
        )

        self.ff = broccoli.transformer.FeedforwardBlock(
            d_model,
            d_model,
            ratio=ff_ratio,
            inner_size=ff_inner_size,
            activation=activation,
            activation_kwargs=activation_kwargs,
            dropout=ff_dropout,
            inner_dropout=ff_inner_dropout,
            outer_dropout=ff_outer_dropout,
            linear_module_up=linear_module,
            linear_module_down=linear_module,
        )

        self.reset_parameters()

    def _residual(self, x, processed, mask, alphas, post_norm_module, pre_norm_next):
        """
        The residual join `EncoderBlock.forward` performs after each branch,
            factored out because this block does it three times rather than
            twice. Returns `(x, input_to_the_next_branch)`.
        """
        processed = mask * processed

        if self.post_norm:
            processed = processed * self.beta
            x = post_norm_module(alphas * x + processed)
            return x, x

        x = x + processed

        if self.pre_norm:
            return x, pre_norm_next(x)

        return x, x

    def forward(self, x, memory):
        if self.training:
            keep_prob = 1 - self.identity_probability
            mask = x.new_empty((x.size(0), 1, 1)).bernoulli_(keep_prob)
            alphas = (self.alpha - 1) * mask + 1
        else:
            mask = 1.0
            alphas = self.alpha

        # Each branch keeps its own norms whichever order it runs in, so
        #     `cross_first` reorders the joins and nothing else. The memory is
        #     normalised by the caller, once, rather than per block.
        attention = (
            lambda h: self.self_attention(h, h, h),
            self.post_attention_norm if self.post_norm else None,
            self.pre_attention_norm if self.pre_norm else None,
        )
        cross = (
            lambda h: self.cross_attention(h, memory, memory),
            self.post_cross_attention_norm if self.post_norm else None,
            self.pre_cross_attention_norm if self.pre_norm else None,
        )
        feedforward = (
            self.ff,
            self.post_mlp_norm if self.post_norm else None,
            self.pre_mlp_norm if self.pre_norm else None,
        )

        branches = (
            [cross, attention, feedforward]
            if self.cross_first
            else [attention, cross, feedforward]
        )

        # The pre-norm each `_residual` is handed is the *next* branch's, which
        #     is why the first one is applied here and the last one is None.
        process_x = branches[0][2](x) if self.pre_norm else x

        for i, (branch, post_norm_module, _) in enumerate(branches):
            next_pre_norm = (
                branches[i + 1][2] if i + 1 < len(branches) else None
            )
            x, process_x = self._residual(
                x,
                branch(process_x),
                mask,
                alphas,
                post_norm_module,
                next_pre_norm,
            )

        return x

    def reset_parameters(self):
        if self.pre_norm:
            self.pre_attention_norm.reset_parameters()
            self.pre_cross_attention_norm.reset_parameters()
            self.pre_mlp_norm.reset_parameters()

        if self.post_norm:
            self.post_attention_norm.reset_parameters()
            self.post_cross_attention_norm.reset_parameters()
            self.post_mlp_norm.reset_parameters()

        self.self_attention.reset_parameters()
        self.cross_attention.reset_parameters()
        self.ff.reset_parameters()


class TransformerDecoder(nn.Module):
    """
    A stack of `DecoderBlock`s over a fixed-length sequence, reading a fixed
        memory. Mirrors `broccoli.transformer.TransformerEncoder`.

    The sequence length is fixed and the mask square over it because broccoli's
        `MHAttention` asserts `query_tokens == seq_len` whenever it is causal,
        so a caller generating symbol by symbol runs the whole stack over a
        full-length buffer at every step. See docs/architecture.md.
    """

    def __init__(
        self,
        seq_len,
        memory_len,
        d_model,
        n_layers,
        n_heads,
        absolute_position_embedding=False,
        relative_position_embedding=False,
        positional_heads=1.0,
        source_size=None,
        ff_ratio=None,
        ff_inner_size=None,
        activation=nn.ReLU,
        activation_kwargs=None,
        ff_dropout=0.0,
        ff_inner_dropout=0.0,
        ff_outer_dropout=0.0,
        msa_dropout=0.0,
        cross_attention_dropout=0.0,
        stochastic_depth=0.0,
        depthwise_linear_stochastic_depth=True,
        linear_module=nn.Linear,
        bos_tokens=0,
        knocking_heads=False,
        return_bos_tokens=False,
        pre_norm=False,
        post_norm=True,
        msa_scaling="d",
        alpha=1.0,
        beta=1.0,
        causal=True,
        cross_first=False,
    ):
        if relative_position_embedding and (source_size is None):
            raise ValueError(
                "`source_size` for TransformerDecoder cannot be None if"
                " `relative_position_embedding` is True"
            )

        if absolute_position_embedding and (seq_len is None):
            raise ValueError(
                "`seq_len` for TransformerDecoder cannot be None if"
                " `absolute_position_embedding` is True"
            )

        super().__init__()

        self.seq_len = seq_len
        self.memory_len = memory_len
        self.d_model = d_model
        self.n_heads = n_heads
        self.n_layers = n_layers
        self._bos_tokens = bos_tokens
        self.return_bos_tokens = return_bos_tokens
        self.alpha = alpha
        self.beta = beta
        self.causal = causal
        self.cross_first = cross_first

        if self._bos_tokens:
            self._bos_token_embedding = nn.Parameter(
                torch.empty(self._bos_tokens, d_model)
            )
        else:
            self._bos_token_embedding = None

        # `seq_len` is only load-bearing for the causal mask and the absolute
        #     position embedding, both of which a non-causal caller can decline
        #     -- `absolute_position_embedding` already raises when it needs a
        #     length and has none.
        self.full_sequence_length = (
            None if self.seq_len is None else self.seq_len + self._bos_tokens
        )

        if absolute_position_embedding:
            self.absolute_position_embedding = nn.Embedding(
                self.full_sequence_length, d_model
            )
        else:
            self.absolute_position_embedding = None

        self.stochastic_depth = stochastic_depth

        assert isinstance(n_layers, int)

        # Identical to `TransformerEncoder`'s schedule, so the two stacks are
        #     regularised on the same terms at the same setting.
        if n_layers == 1:
            self.stochastic_depth_probabilities = [0.0]
        elif depthwise_linear_stochastic_depth:
            step_size = self.stochastic_depth / (n_layers - 1)
            self.stochastic_depth_probabilities = [
                i * step_size for i in range(n_layers)
            ]
        else:
            self.stochastic_depth_probabilities = [
                self.stochastic_depth for _ in range(n_layers)
            ]

        self.blocks = nn.ModuleList(
            [
                DecoderBlock(
                    self.full_sequence_length,
                    memory_len,
                    d_model,
                    n_heads,
                    relative_position_embedding=relative_position_embedding,
                    positional_heads=positional_heads,
                    source_size=source_size,
                    bos_tokens=bos_tokens,
                    knocking_heads=knocking_heads,
                    ff_ratio=ff_ratio,
                    ff_inner_size=ff_inner_size,
                    activation=activation,
                    activation_kwargs=activation_kwargs,
                    msa_scaling=msa_scaling,
                    ff_dropout=ff_dropout,
                    ff_inner_dropout=ff_inner_dropout,
                    ff_outer_dropout=ff_outer_dropout,
                    msa_dropout=msa_dropout,
                    cross_attention_dropout=cross_attention_dropout,
                    identity_probability=self.stochastic_depth_probabilities[i],
                    linear_module=linear_module,
                    pre_norm=pre_norm,
                    post_norm=post_norm,
                    alpha=alpha,
                    beta=beta,
                    causal=causal,
                    cross_first=cross_first,
                )
                for i in range(n_layers)
            ]
        )

        self.reset_parameters()

    def preprocess(self, x):
        if self._bos_tokens:
            x = torch.cat(
                [self._bos_token_embedding.expand(x.size(0), -1, -1), x], dim=1
            )

        if self.absolute_position_embedding is not None:
            position_embedding = self.absolute_position_embedding(
                torch.arange(
                    0, self.full_sequence_length, dtype=torch.long, device=x.device
                ).unsqueeze(0) # to shape (1, seq_len) to broadcast over batch
            )
            x = x + position_embedding

        return x

    def forward(self, x, memory):
        """
        Args:
            x: (batch, seq_len, d_model), the sequence so far. Positions after
                the caller's cursor are never read by positions before it, so
                they may hold anything.
            memory: (batch, memory_len, d_model), already normalised.

        Returns:
            (batch, seq_len, d_model), or `seq_len + bos_tokens` if
                `return_bos_tokens`.
        """
        x = self.preprocess(x)

        for block in self.blocks:
            x = checkpoint(block, x, memory, use_reentrant=False)

        if self._bos_tokens and not self.return_bos_tokens:
            return x[:, self._bos_tokens :, :]

        return x

    def reset_parameters(self):
        # Normal init, as broccoli initialises its own bos tokens.
        if self._bos_token_embedding is not None:
            nn.init.normal_(self._bos_token_embedding, mean=0.0, std=1.0)

        if self.absolute_position_embedding is not None:
            self.absolute_position_embedding.reset_parameters()

        for block in self.blocks:
            block.reset_parameters()
