"""
A Transformer decoder, composed from broccoli's primitives.

broccoli has no decoder: `TransformerEncoder` and its `EncoderBlock` are
    self-attention and feedforward only, and every cross-attention in this
    repository until now has been a single `MHAttention` sitting *between*
    stacks -- `SenderTransformerLM`'s Perceiver IO encode/decode pair, and
    `TransformerCrossAttentionComparer`'s bridge from the message to the
    referents.

    A speaker that generates left to right needs the other arrangement: a
    causal self-attention over the symbols emitted so far and a cross-attention
    into a fixed memory, both inside every block, so that each layer can revisit
    the memory in the light of what the layer below it made of the prefix.

The blocks below mirror `broccoli.transformer.EncoderBlock` deliberately
    closely -- same residual scheme, same `alpha`/`beta` placement, same
    stochastic-depth draw, same pre/post-norm branches -- with one extra
    sublayer between the self-attention and the feedforward. Everything inside
    them is a broccoli module; what this file adds is the wiring, so that a
    change to broccoli's attention or feedforward reaches this stack too.

As in `receiver.py` and `sender.py`, every broccoli argument is passed
    explicitly, including the inert ones, because broccoli's defaults have
    changed underneath this repository before.
"""

import torch
import torch.nn as nn
from torch.utils.checkpoint import checkpoint

import broccoli
from broccoli.rope import RotaryEmbedding


class DecoderBlock(nn.Module):
    """
    One decoder layer: causal self-attention, then cross-attention into a
        memory, then a feedforward, each on its own residual branch.

    Three branches rather than `EncoderBlock`'s two, which is exactly the
        configuration DeepNorm derived its *decoder* constants for -- see
        `model_util.deepnorm_constants`, and note that a stack built from these
        blocks must ask for `decoder=True` or it will open scaled for the wrong
        number of branches.

    Stochastic depth is drawn inside `forward`, as `EncoderBlock` draws it, and
        the same mask is shared by all three branches of a block so that a
        dropped block is the identity rather than a partial one.

        Note what that means for a speaker: `SenderTransformerLM` runs this
        stack once per symbol, so a message's five positions are generated by
        five independent draws -- five sub-networks, not one. That is a
        deliberate choice, not an oversight. Hoisting the draw to once per
        message would be the alternative, and would make the regulariser mean
        "drop this block for this utterance" instead of "drop it for this
        symbol". Both are defensible; this one keeps the block a faithful
        mirror of broccoli's, with no bespoke mask plumbing to drift out of
        sync when broccoli's changes.
    """

    def __init__(
        self,
        seq_len,
        memory_len,
        d_model,
        n_heads,
        relative_position_embedding=False,
        positional_heads=1.0,
        source_size=None,
        bos_tokens=0,
        knocking_heads=False,
        ff_ratio=None,
        ff_inner_size=None,
        activation=nn.ReLU,
        activation_kwargs=None,
        msa_scaling="d",
        ff_dropout=0.0,
        ff_inner_dropout=0.0,
        ff_outer_dropout=0.0,
        msa_dropout=0.0,
        cross_attention_dropout=0.0,
        identity_probability=0.0,
        linear_module=nn.Linear,
        pre_norm=False,
        post_norm=True,
        alpha=1.0,
        beta=1.0,
    ):
        """
        Args:
            seq_len: length of the sequence being decoded, including any
                `bos_tokens` prefix. The causal mask is square over this, so it
                is fixed -- see `TransformerDecoder` for why that suits the
                caller.
            memory_len: length of the array being cross-attended into. Recorded
                for the caller's benefit and to size nothing: the
                cross-attention is not causal, so it needs no mask.
        """
        super().__init__()

        if pre_norm and post_norm:
            raise ValueError("A transformer cannot be both prenorm and postnorm.")

        self.n_heads = n_heads
        self.seq_len = seq_len
        self.memory_len = memory_len

        self.pre_norm = pre_norm
        self.post_norm = post_norm

        self.alpha = alpha
        self.beta = beta

        self.identity_probability = identity_probability

        if self.pre_norm:
            self.pre_attention_norm = nn.RMSNorm(d_model)
            self.pre_cross_attention_norm = nn.RMSNorm(d_model)
            self.pre_mlp_norm = nn.RMSNorm(d_model)

        if self.post_norm:
            self.post_attention_norm = nn.RMSNorm(d_model)
            self.post_cross_attention_norm = nn.RMSNorm(d_model)
            self.post_mlp_norm = nn.RMSNorm(d_model)

        # Built here rather than taken as an argument, mirroring `EncoderBlock`:
        #     each block owns its own frequencies.
        if relative_position_embedding:
            max_freq = int(max(source_size) / 2)
            dim = d_model if d_model < 16 else 16
            self.rotary_embedding = RotaryEmbedding(
                dim=dim, freqs_for="pixel", max_freq=max_freq
            )
        else:
            self.rotary_embedding = None

        self.self_attention = broccoli.transformer.MHAttention(
            d_model,
            n_heads,
            dropout=msa_dropout,
            causal=True, # The whole point of the block
            seq_len=seq_len,
            linear_module=linear_module,
            bos_tokens=bos_tokens,
            knocking_heads=knocking_heads,
            rotary_embedding=self.rotary_embedding,
            positional_heads=positional_heads,
            source_size=source_size,
            scaling=msa_scaling,
        )

        # No positional information on either side. The queries carry the
        #     decoder's own order, through the absolute position embedding and
        #     the rotary self-attention above; the memory's order is already
        #     baked into it by whatever produced it. This mirrors how
        #     `SenderTransformerLM` pins its two standalone cross-attentions,
        #     including `positional_heads` at the repo-wide 1.0 -- inert while
        #     `rotary_embedding` is None, and pinned so that turning rotary on
        #     here could not quietly introduce a head partition. broccoli's own
        #     defaults differ by class (0.25 on `MHAttention`, 0.5 on
        #     `TransformerEncoder`), so neither is a value to inherit.
        self.cross_attention = broccoli.transformer.MHAttention(
            d_model,
            n_heads,
            dropout=cross_attention_dropout,
            causal=False, # Whole memory informs every position
            seq_len=seq_len,
            linear_module=linear_module,
            bos_tokens=0,
            knocking_heads=False,
            rotary_embedding=None,
            positional_heads=1.0,
            source_size=None,
            scaling=msa_scaling,
        )

        self.ff = broccoli.transformer.FeedforwardBlock(
            d_model,
            d_model,
            ratio=ff_ratio,
            inner_size=ff_inner_size,
            activation=activation,
            activation_kwargs=activation_kwargs,
            dropout=ff_dropout,
            inner_dropout=ff_inner_dropout,
            outer_dropout=ff_outer_dropout,
            linear_module_up=linear_module,
            linear_module_down=linear_module,
        )

        self.reset_parameters()

    def _residual(self, x, processed, mask, alphas, post_norm_module, pre_norm_next):
        """
        The residual join `EncoderBlock.forward` performs after each branch,
            factored out because this block does it three times rather than
            twice. Returns `(x, input_to_the_next_branch)`.
        """
        processed = mask * processed

        if self.post_norm:
            processed = processed * self.beta
            x = post_norm_module(alphas * x + processed)
            return x, x

        x = x + processed

        if self.pre_norm:
            return x, pre_norm_next(x)

        return x, x

    def forward(self, x, memory):
        if self.training:
            keep_prob = 1 - self.identity_probability
            mask = x.new_empty((x.size(0), 1, 1)).bernoulli_(keep_prob)
            alphas = (self.alpha - 1) * mask + 1
        else:
            mask = 1.0
            alphas = self.alpha

        process_x = self.pre_attention_norm(x) if self.pre_norm else x

        processed = self.self_attention(process_x, process_x, process_x)
        x, process_x = self._residual(
            x,
            processed,
            mask,
            alphas,
            self.post_attention_norm if self.post_norm else None,
            self.pre_cross_attention_norm if self.pre_norm else None,
        )

        # The memory is normalised by the caller, once, rather than here: it is
        #     the same array for every block and every step of the decoding
        #     loop, so normalising it per block would repeat identical work
        #     `layers * content_length` times per batch.
        processed = self.cross_attention(process_x, memory, memory)
        x, process_x = self._residual(
            x,
            processed,
            mask,
            alphas,
            self.post_cross_attention_norm if self.post_norm else None,
            self.pre_mlp_norm if self.pre_norm else None,
        )

        processed = self.ff(process_x)
        x, _ = self._residual(
            x,
            processed,
            mask,
            alphas,
            self.post_mlp_norm if self.post_norm else None,
            None,
        )

        return x

    def reset_parameters(self):
        if self.pre_norm:
            self.pre_attention_norm.reset_parameters()
            self.pre_cross_attention_norm.reset_parameters()
            self.pre_mlp_norm.reset_parameters()

        if self.post_norm:
            self.post_attention_norm.reset_parameters()
            self.post_cross_attention_norm.reset_parameters()
            self.post_mlp_norm.reset_parameters()

        self.self_attention.reset_parameters()
        self.cross_attention.reset_parameters()
        self.ff.reset_parameters()


class TransformerDecoder(nn.Module):
    """
    A stack of `DecoderBlock`s over a fixed-length sequence, reading a fixed
        memory.

    Mirrors `broccoli.transformer.TransformerEncoder`: it owns the absolute
        position embedding and the learned `bos_tokens` prefix, applies them in
        `preprocess`, checkpoints each block, and strips the prefix on the way
        out unless asked to keep it.

    The sequence length is fixed and the mask is square over it, because
        broccoli's `MHAttention` asserts `query_tokens == seq_len` whenever it
        is causal. A caller generating symbol by symbol therefore runs the whole
        stack over a full-length buffer at every step, filling one more position
        each time; the causal mask makes the positions ahead of the cursor
        unable to reach the ones behind it, so the unwritten tail is inert and
        the result is exact. See `SenderTransformerLM.decode`.
    """

    def __init__(
        self,
        seq_len,
        memory_len,
        d_model,
        n_layers,
        n_heads,
        absolute_position_embedding=False,
        relative_position_embedding=False,
        positional_heads=1.0,
        source_size=None,
        ff_ratio=None,
        ff_inner_size=None,
        activation=nn.ReLU,
        activation_kwargs=None,
        ff_dropout=0.0,
        ff_inner_dropout=0.0,
        ff_outer_dropout=0.0,
        msa_dropout=0.0,
        cross_attention_dropout=0.0,
        stochastic_depth=0.0,
        depthwise_linear_stochastic_depth=True,
        linear_module=nn.Linear,
        bos_tokens=0,
        knocking_heads=False,
        return_bos_tokens=False,
        pre_norm=False,
        post_norm=True,
        msa_scaling="d",
        alpha=1.0,
        beta=1.0,
    ):
        if relative_position_embedding and (source_size is None):
            raise ValueError(
                "`source_size` for TransformerDecoder cannot be None if"
                " `relative_position_embedding` is True"
            )

        if absolute_position_embedding and (seq_len is None):
            raise ValueError(
                "`seq_len` for TransformerDecoder cannot be None if"
                " `absolute_position_embedding` is True"
            )

        super().__init__()

        self.seq_len = seq_len
        self.memory_len = memory_len
        self.d_model = d_model
        self.n_heads = n_heads
        self.n_layers = n_layers
        self._bos_tokens = bos_tokens
        self.return_bos_tokens = return_bos_tokens
        self.alpha = alpha
        self.beta = beta

        if self._bos_tokens:
            self._bos_token_embedding = nn.Parameter(
                torch.empty(self._bos_tokens, d_model)
            )
        else:
            self._bos_token_embedding = None

        self.full_sequence_length = self.seq_len + self._bos_tokens

        if absolute_position_embedding:
            self.absolute_position_embedding = nn.Embedding(
                self.full_sequence_length, d_model
            )
        else:
            self.absolute_position_embedding = None

        self.stochastic_depth = stochastic_depth

        assert isinstance(n_layers, int)

        # Identical to `TransformerEncoder`'s schedule, including its treatment
        #     of the single-layer case, so that the two stacks are regularised
        #     on the same terms at the same setting.
        if n_layers == 1:
            self.stochastic_depth_probabilities = [0.0]
        elif depthwise_linear_stochastic_depth:
            step_size = self.stochastic_depth / (n_layers - 1)
            self.stochastic_depth_probabilities = [
                i * step_size for i in range(n_layers)
            ]
        else:
            self.stochastic_depth_probabilities = [
                self.stochastic_depth for _ in range(n_layers)
            ]

        self.blocks = nn.ModuleList(
            [
                DecoderBlock(
                    self.full_sequence_length,
                    memory_len,
                    d_model,
                    n_heads,
                    relative_position_embedding=relative_position_embedding,
                    positional_heads=positional_heads,
                    source_size=source_size,
                    bos_tokens=bos_tokens,
                    knocking_heads=knocking_heads,
                    ff_ratio=ff_ratio,
                    ff_inner_size=ff_inner_size,
                    activation=activation,
                    activation_kwargs=activation_kwargs,
                    msa_scaling=msa_scaling,
                    ff_dropout=ff_dropout,
                    ff_inner_dropout=ff_inner_dropout,
                    ff_outer_dropout=ff_outer_dropout,
                    msa_dropout=msa_dropout,
                    cross_attention_dropout=cross_attention_dropout,
                    identity_probability=self.stochastic_depth_probabilities[i],
                    linear_module=linear_module,
                    pre_norm=pre_norm,
                    post_norm=post_norm,
                    alpha=alpha,
                    beta=beta,
                )
                for i in range(n_layers)
            ]
        )

        self.reset_parameters()

    def preprocess(self, x):
        if self._bos_tokens:
            x = torch.cat(
                [self._bos_token_embedding.expand(x.size(0), -1, -1), x], dim=1
            )

        if self.absolute_position_embedding is not None:
            position_embedding = self.absolute_position_embedding(
                torch.arange(
                    0, self.full_sequence_length, dtype=torch.long, device=x.device
                ).unsqueeze(0) # to shape (1, seq_len) to broadcast over batch
            )
            x = x + position_embedding

        return x

    def forward(self, x, memory):
        """
        Args:
            x: (batch, seq_len, d_model), the sequence so far. Positions after
                the caller's cursor are never read by positions before it, so
                they may hold anything.
            memory: (batch, memory_len, d_model), already normalised.

        Returns:
            (batch, seq_len, d_model), or `seq_len + bos_tokens` if
                `return_bos_tokens`.
        """
        x = self.preprocess(x)

        for block in self.blocks:
            x = checkpoint(block, x, memory, use_reentrant=False)

        if self._bos_tokens and not self.return_bos_tokens:
            return x[:, self._bos_tokens :, :]

        return x

    def reset_parameters(self):
        # Normal init, as broccoli initialises its own bos tokens.
        if self._bos_token_embedding is not None:
            nn.init.normal_(self._bos_token_embedding, mean=0.0, std=1.0)

        if self.absolute_position_embedding is not None:
            self.absolute_position_embedding.reset_parameters()

        for block in self.blocks:
            block.reset_parameters()
